openapi: 3.0.0
info:
  title: JSON_API
  version: '1.0'
  contact:
    name: Nelsen Lim
    email: nelsen@dealpos.com
  description: DEALPOS DEVELOPER API
servers:
  - url: 'https://nelsenlim.dealpos.net'
paths:
  /Category:
    post:
      summary: ''
      operationId: post-Category
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    ID: 273d1184-a64b-4d2d-ad98-8b38b19c3ffb
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example-1:
                value:
                  Name: Top/Men
        description: ''
components:
  schemas: {}
  securitySchemes:
    jwt-token:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
security:
  - jwt-token: []
